In [2]:
import numpy as np
d3 = np.random.rand(2,3)<0.8
print d3

[[False  True  True]
 [ True  True  True]]


In [3]:
print d3

[[ True  True False]
 [ True  True False]]


In [5]:
#dropout函数的实现  
def dropout(x, level):  
    if level < 0. or level >= 1:#level是概率值，必须在0~1之间  
        raise Exception('Dropout level must be in interval [0, 1[.')  
    retain_prob = 1. - level  
    #我们通过binomial函数，生成与x一样的维数向量。binomial函数就像抛硬币一样，我们可以把每个神经元当做抛硬币一样  
    #硬币 正面的概率为p，n表示每个神经元试验的次数  
    #因为我们每个神经元只需要抛一次就可以了所以n=1，size参数是我们有多少个硬币。  
    sample=np.random.binomial(n=1,p=retain_prob,size=x.shape)#即将生成一个0、1分布的向量，0表示这个神经元被屏蔽，不工作了，也就是dropout了  
    print sample  
    x *=sample#0、1与x相乘，我们就可以屏蔽某些神经元，让它们的值变为0  
    print x  
    x /= retain_prob  
  
    return x  
#对dropout的测试，大家可以跑一下上面的函数，了解一个输入x向量，经过dropout的结果  
x=np.asarray([1,2,3,4,5,6,7,8,9,10],dtype=np.float32)  
dropout(x,0.4)

[0 0 1 1 1 0 1 1 1 1]
[  0.   0.   3.   4.   5.   0.   7.   8.   9.  10.]


array([  0.        ,   0.        ,   5.        ,   6.66666651,
         8.33333302,   0.        ,  11.66666603,  13.33333302,
        14.99999905,  16.66666603], dtype=float32)